services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: payper_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - payper-network

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: payper_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - payper-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: payper_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - output-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - payper-network
    command: --default-authentication-plugin=mysql_native_password

  node:
    image: node:22-alpine3.20
    container_name: payper_node
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "5173:5173"
    command: npm run dev
    networks:
      - payper-network

networks:
  payper-network:
    driver: bridge

volumes:
  output-mysql-data:
